//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace Ehsani.ir.payamtube {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.79.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="smsSendWebServiceSoap", Namespace="http://tempuri.org/")]
    public partial class smsSendWebService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback LoginOperationCompleted;
        
        private System.Threading.SendOrPostCallback SendSmsOperationCompleted;
        
        private System.Threading.SendOrPostCallback SendSingleSmsOperationCompleted;
        
        private System.Threading.SendOrPostCallback SendSmsUDHOperationCompleted;
        
        private System.Threading.SendOrPostCallback getCreditOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetReceiveSMSWithNumberOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetReceiveSMSOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetCountAllOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetCountOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetDeliveryOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetSingleDeliveryOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetAllDeliveryOperationCompleted;
        
        private System.Threading.SendOrPostCallback SendFutureSmsOperationCompleted;
        
        private System.Threading.SendOrPostCallback DeleteFutureSmsOperationCompleted;
        
        private System.Threading.SendOrPostCallback CheckSendFutureOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public smsSendWebService() {
            this.Url = global::Ehsani.Properties.Settings.Default.Ehsani_ir_payamtube_smsSendWebService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event LoginCompletedEventHandler LoginCompleted;
        
        /// <remarks/>
        public event SendSmsCompletedEventHandler SendSmsCompleted;
        
        /// <remarks/>
        public event SendSingleSmsCompletedEventHandler SendSingleSmsCompleted;
        
        /// <remarks/>
        public event SendSmsUDHCompletedEventHandler SendSmsUDHCompleted;
        
        /// <remarks/>
        public event getCreditCompletedEventHandler getCreditCompleted;
        
        /// <remarks/>
        public event GetReceiveSMSWithNumberCompletedEventHandler GetReceiveSMSWithNumberCompleted;
        
        /// <remarks/>
        public event GetReceiveSMSCompletedEventHandler GetReceiveSMSCompleted;
        
        /// <remarks/>
        public event GetCountAllCompletedEventHandler GetCountAllCompleted;
        
        /// <remarks/>
        public event GetCountCompletedEventHandler GetCountCompleted;
        
        /// <remarks/>
        public event GetDeliveryCompletedEventHandler GetDeliveryCompleted;
        
        /// <remarks/>
        public event GetSingleDeliveryCompletedEventHandler GetSingleDeliveryCompleted;
        
        /// <remarks/>
        public event GetAllDeliveryCompletedEventHandler GetAllDeliveryCompleted;
        
        /// <remarks/>
        public event SendFutureSmsCompletedEventHandler SendFutureSmsCompleted;
        
        /// <remarks/>
        public event DeleteFutureSmsCompletedEventHandler DeleteFutureSmsCompleted;
        
        /// <remarks/>
        public event CheckSendFutureCompletedEventHandler CheckSendFutureCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Login", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int Login(string UserName, string Pass, string Domain) {
            object[] results = this.Invoke("Login", new object[] {
                        UserName,
                        Pass,
                        Domain});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void LoginAsync(string UserName, string Pass, string Domain) {
            this.LoginAsync(UserName, Pass, Domain, null);
        }
        
        /// <remarks/>
        public void LoginAsync(string UserName, string Pass, string Domain, object userState) {
            if ((this.LoginOperationCompleted == null)) {
                this.LoginOperationCompleted = new System.Threading.SendOrPostCallback(this.OnLoginOperationCompleted);
            }
            this.InvokeAsync("Login", new object[] {
                        UserName,
                        Pass,
                        Domain}, this.LoginOperationCompleted, userState);
        }
        
        private void OnLoginOperationCompleted(object arg) {
            if ((this.LoginCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.LoginCompleted(this, new LoginCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/SendSms", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public long[] SendSms(string[] SmsText, string[] MobileNumber, string SenderNumber, SendType sendType, SmsMode smsMode) {
            object[] results = this.Invoke("SendSms", new object[] {
                        SmsText,
                        MobileNumber,
                        SenderNumber,
                        sendType,
                        smsMode});
            return ((long[])(results[0]));
        }
        
        /// <remarks/>
        public void SendSmsAsync(string[] SmsText, string[] MobileNumber, string SenderNumber, SendType sendType, SmsMode smsMode) {
            this.SendSmsAsync(SmsText, MobileNumber, SenderNumber, sendType, smsMode, null);
        }
        
        /// <remarks/>
        public void SendSmsAsync(string[] SmsText, string[] MobileNumber, string SenderNumber, SendType sendType, SmsMode smsMode, object userState) {
            if ((this.SendSmsOperationCompleted == null)) {
                this.SendSmsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSendSmsOperationCompleted);
            }
            this.InvokeAsync("SendSms", new object[] {
                        SmsText,
                        MobileNumber,
                        SenderNumber,
                        sendType,
                        smsMode}, this.SendSmsOperationCompleted, userState);
        }
        
        private void OnSendSmsOperationCompleted(object arg) {
            if ((this.SendSmsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SendSmsCompleted(this, new SendSmsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/SendSingleSms", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public long SendSingleSms(string SmsText, string MobileNumber, string SenderNumber, SmsMode smsMode) {
            object[] results = this.Invoke("SendSingleSms", new object[] {
                        SmsText,
                        MobileNumber,
                        SenderNumber,
                        smsMode});
            return ((long)(results[0]));
        }
        
        /// <remarks/>
        public void SendSingleSmsAsync(string SmsText, string MobileNumber, string SenderNumber, SmsMode smsMode) {
            this.SendSingleSmsAsync(SmsText, MobileNumber, SenderNumber, smsMode, null);
        }
        
        /// <remarks/>
        public void SendSingleSmsAsync(string SmsText, string MobileNumber, string SenderNumber, SmsMode smsMode, object userState) {
            if ((this.SendSingleSmsOperationCompleted == null)) {
                this.SendSingleSmsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSendSingleSmsOperationCompleted);
            }
            this.InvokeAsync("SendSingleSms", new object[] {
                        SmsText,
                        MobileNumber,
                        SenderNumber,
                        smsMode}, this.SendSingleSmsOperationCompleted, userState);
        }
        
        private void OnSendSingleSmsOperationCompleted(object arg) {
            if ((this.SendSingleSmsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SendSingleSmsCompleted(this, new SendSingleSmsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/SendSmsUDH", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public long[] SendSmsUDH(string[] SmsText, string[] MobileNumber, string SenderNumber, SendType sendType, SmsMode smsMode, string[] UDH) {
            object[] results = this.Invoke("SendSmsUDH", new object[] {
                        SmsText,
                        MobileNumber,
                        SenderNumber,
                        sendType,
                        smsMode,
                        UDH});
            return ((long[])(results[0]));
        }
        
        /// <remarks/>
        public void SendSmsUDHAsync(string[] SmsText, string[] MobileNumber, string SenderNumber, SendType sendType, SmsMode smsMode, string[] UDH) {
            this.SendSmsUDHAsync(SmsText, MobileNumber, SenderNumber, sendType, smsMode, UDH, null);
        }
        
        /// <remarks/>
        public void SendSmsUDHAsync(string[] SmsText, string[] MobileNumber, string SenderNumber, SendType sendType, SmsMode smsMode, string[] UDH, object userState) {
            if ((this.SendSmsUDHOperationCompleted == null)) {
                this.SendSmsUDHOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSendSmsUDHOperationCompleted);
            }
            this.InvokeAsync("SendSmsUDH", new object[] {
                        SmsText,
                        MobileNumber,
                        SenderNumber,
                        sendType,
                        smsMode,
                        UDH}, this.SendSmsUDHOperationCompleted, userState);
        }
        
        private void OnSendSmsUDHOperationCompleted(object arg) {
            if ((this.SendSmsUDHCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SendSmsUDHCompleted(this, new SendSmsUDHCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/getCredit", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string getCredit() {
            object[] results = this.Invoke("getCredit", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void getCreditAsync() {
            this.getCreditAsync(null);
        }
        
        /// <remarks/>
        public void getCreditAsync(object userState) {
            if ((this.getCreditOperationCompleted == null)) {
                this.getCreditOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetCreditOperationCompleted);
            }
            this.InvokeAsync("getCredit", new object[0], this.getCreditOperationCompleted, userState);
        }
        
        private void OngetCreditOperationCompleted(object arg) {
            if ((this.getCreditCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getCreditCompleted(this, new getCreditCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetReceiveSMSWithNumber", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ReceiveSMS[] GetReceiveSMSWithNumber(ReceiveType RecType, string LineNumber, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] System.Nullable<int> Count, string FromDate, string ToDate) {
            object[] results = this.Invoke("GetReceiveSMSWithNumber", new object[] {
                        RecType,
                        LineNumber,
                        Count,
                        FromDate,
                        ToDate});
            return ((ReceiveSMS[])(results[0]));
        }
        
        /// <remarks/>
        public void GetReceiveSMSWithNumberAsync(ReceiveType RecType, string LineNumber, System.Nullable<int> Count, string FromDate, string ToDate) {
            this.GetReceiveSMSWithNumberAsync(RecType, LineNumber, Count, FromDate, ToDate, null);
        }
        
        /// <remarks/>
        public void GetReceiveSMSWithNumberAsync(ReceiveType RecType, string LineNumber, System.Nullable<int> Count, string FromDate, string ToDate, object userState) {
            if ((this.GetReceiveSMSWithNumberOperationCompleted == null)) {
                this.GetReceiveSMSWithNumberOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetReceiveSMSWithNumberOperationCompleted);
            }
            this.InvokeAsync("GetReceiveSMSWithNumber", new object[] {
                        RecType,
                        LineNumber,
                        Count,
                        FromDate,
                        ToDate}, this.GetReceiveSMSWithNumberOperationCompleted, userState);
        }
        
        private void OnGetReceiveSMSWithNumberOperationCompleted(object arg) {
            if ((this.GetReceiveSMSWithNumberCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetReceiveSMSWithNumberCompleted(this, new GetReceiveSMSWithNumberCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetReceiveSMS", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ReceiveSMS[] GetReceiveSMS(ReceiveType RecType, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] System.Nullable<int> Count, string FromDate, string ToDate) {
            object[] results = this.Invoke("GetReceiveSMS", new object[] {
                        RecType,
                        Count,
                        FromDate,
                        ToDate});
            return ((ReceiveSMS[])(results[0]));
        }
        
        /// <remarks/>
        public void GetReceiveSMSAsync(ReceiveType RecType, System.Nullable<int> Count, string FromDate, string ToDate) {
            this.GetReceiveSMSAsync(RecType, Count, FromDate, ToDate, null);
        }
        
        /// <remarks/>
        public void GetReceiveSMSAsync(ReceiveType RecType, System.Nullable<int> Count, string FromDate, string ToDate, object userState) {
            if ((this.GetReceiveSMSOperationCompleted == null)) {
                this.GetReceiveSMSOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetReceiveSMSOperationCompleted);
            }
            this.InvokeAsync("GetReceiveSMS", new object[] {
                        RecType,
                        Count,
                        FromDate,
                        ToDate}, this.GetReceiveSMSOperationCompleted, userState);
        }
        
        private void OnGetReceiveSMSOperationCompleted(object arg) {
            if ((this.GetReceiveSMSCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetReceiveSMSCompleted(this, new GetReceiveSMSCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetCountAll", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int GetCountAll() {
            object[] results = this.Invoke("GetCountAll", new object[0]);
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void GetCountAllAsync() {
            this.GetCountAllAsync(null);
        }
        
        /// <remarks/>
        public void GetCountAllAsync(object userState) {
            if ((this.GetCountAllOperationCompleted == null)) {
                this.GetCountAllOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetCountAllOperationCompleted);
            }
            this.InvokeAsync("GetCountAll", new object[0], this.GetCountAllOperationCompleted, userState);
        }
        
        private void OnGetCountAllOperationCompleted(object arg) {
            if ((this.GetCountAllCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetCountAllCompleted(this, new GetCountAllCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetCount", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int GetCount(string LineNumber) {
            object[] results = this.Invoke("GetCount", new object[] {
                        LineNumber});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void GetCountAsync(string LineNumber) {
            this.GetCountAsync(LineNumber, null);
        }
        
        /// <remarks/>
        public void GetCountAsync(string LineNumber, object userState) {
            if ((this.GetCountOperationCompleted == null)) {
                this.GetCountOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetCountOperationCompleted);
            }
            this.InvokeAsync("GetCount", new object[] {
                        LineNumber}, this.GetCountOperationCompleted, userState);
        }
        
        private void OnGetCountOperationCompleted(object arg) {
            if ((this.GetCountCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetCountCompleted(this, new GetCountCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetDelivery", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int[] GetDelivery(long[] smsId) {
            object[] results = this.Invoke("GetDelivery", new object[] {
                        smsId});
            return ((int[])(results[0]));
        }
        
        /// <remarks/>
        public void GetDeliveryAsync(long[] smsId) {
            this.GetDeliveryAsync(smsId, null);
        }
        
        /// <remarks/>
        public void GetDeliveryAsync(long[] smsId, object userState) {
            if ((this.GetDeliveryOperationCompleted == null)) {
                this.GetDeliveryOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetDeliveryOperationCompleted);
            }
            this.InvokeAsync("GetDelivery", new object[] {
                        smsId}, this.GetDeliveryOperationCompleted, userState);
        }
        
        private void OnGetDeliveryOperationCompleted(object arg) {
            if ((this.GetDeliveryCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetDeliveryCompleted(this, new GetDeliveryCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetSingleDelivery", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int GetSingleDelivery(long SmsId) {
            object[] results = this.Invoke("GetSingleDelivery", new object[] {
                        SmsId});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void GetSingleDeliveryAsync(long SmsId) {
            this.GetSingleDeliveryAsync(SmsId, null);
        }
        
        /// <remarks/>
        public void GetSingleDeliveryAsync(long SmsId, object userState) {
            if ((this.GetSingleDeliveryOperationCompleted == null)) {
                this.GetSingleDeliveryOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetSingleDeliveryOperationCompleted);
            }
            this.InvokeAsync("GetSingleDelivery", new object[] {
                        SmsId}, this.GetSingleDeliveryOperationCompleted, userState);
        }
        
        private void OnGetSingleDeliveryOperationCompleted(object arg) {
            if ((this.GetSingleDeliveryCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetSingleDeliveryCompleted(this, new GetSingleDeliveryCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetAllDelivery", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int[] GetAllDelivery(long[] SmsId, string LineNumber) {
            object[] results = this.Invoke("GetAllDelivery", new object[] {
                        SmsId,
                        LineNumber});
            return ((int[])(results[0]));
        }
        
        /// <remarks/>
        public void GetAllDeliveryAsync(long[] SmsId, string LineNumber) {
            this.GetAllDeliveryAsync(SmsId, LineNumber, null);
        }
        
        /// <remarks/>
        public void GetAllDeliveryAsync(long[] SmsId, string LineNumber, object userState) {
            if ((this.GetAllDeliveryOperationCompleted == null)) {
                this.GetAllDeliveryOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetAllDeliveryOperationCompleted);
            }
            this.InvokeAsync("GetAllDelivery", new object[] {
                        SmsId,
                        LineNumber}, this.GetAllDeliveryOperationCompleted, userState);
        }
        
        private void OnGetAllDeliveryOperationCompleted(object arg) {
            if ((this.GetAllDeliveryCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetAllDeliveryCompleted(this, new GetAllDeliveryCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/SendFutureSms", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int SendFutureSms(string LineNumber, string ReceiveNumber, string Date, string Time, string SmsText) {
            object[] results = this.Invoke("SendFutureSms", new object[] {
                        LineNumber,
                        ReceiveNumber,
                        Date,
                        Time,
                        SmsText});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void SendFutureSmsAsync(string LineNumber, string ReceiveNumber, string Date, string Time, string SmsText) {
            this.SendFutureSmsAsync(LineNumber, ReceiveNumber, Date, Time, SmsText, null);
        }
        
        /// <remarks/>
        public void SendFutureSmsAsync(string LineNumber, string ReceiveNumber, string Date, string Time, string SmsText, object userState) {
            if ((this.SendFutureSmsOperationCompleted == null)) {
                this.SendFutureSmsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSendFutureSmsOperationCompleted);
            }
            this.InvokeAsync("SendFutureSms", new object[] {
                        LineNumber,
                        ReceiveNumber,
                        Date,
                        Time,
                        SmsText}, this.SendFutureSmsOperationCompleted, userState);
        }
        
        private void OnSendFutureSmsOperationCompleted(object arg) {
            if ((this.SendFutureSmsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SendFutureSmsCompleted(this, new SendFutureSmsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/DeleteFutureSms", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int DeleteFutureSms(int FutureId) {
            object[] results = this.Invoke("DeleteFutureSms", new object[] {
                        FutureId});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void DeleteFutureSmsAsync(int FutureId) {
            this.DeleteFutureSmsAsync(FutureId, null);
        }
        
        /// <remarks/>
        public void DeleteFutureSmsAsync(int FutureId, object userState) {
            if ((this.DeleteFutureSmsOperationCompleted == null)) {
                this.DeleteFutureSmsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnDeleteFutureSmsOperationCompleted);
            }
            this.InvokeAsync("DeleteFutureSms", new object[] {
                        FutureId}, this.DeleteFutureSmsOperationCompleted, userState);
        }
        
        private void OnDeleteFutureSmsOperationCompleted(object arg) {
            if ((this.DeleteFutureSmsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.DeleteFutureSmsCompleted(this, new DeleteFutureSmsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/CheckSendFuture", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string CheckSendFuture(int FutureSmsId) {
            object[] results = this.Invoke("CheckSendFuture", new object[] {
                        FutureSmsId});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void CheckSendFutureAsync(int FutureSmsId) {
            this.CheckSendFutureAsync(FutureSmsId, null);
        }
        
        /// <remarks/>
        public void CheckSendFutureAsync(int FutureSmsId, object userState) {
            if ((this.CheckSendFutureOperationCompleted == null)) {
                this.CheckSendFutureOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCheckSendFutureOperationCompleted);
            }
            this.InvokeAsync("CheckSendFuture", new object[] {
                        FutureSmsId}, this.CheckSendFutureOperationCompleted, userState);
        }
        
        private void OnCheckSendFutureOperationCompleted(object arg) {
            if ((this.CheckSendFutureCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CheckSendFutureCompleted(this, new CheckSendFutureCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.79.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public enum SendType {
        
        /// <remarks/>
        StaticText,
        
        /// <remarks/>
        DynamicText,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.79.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public enum SmsMode {
        
        /// <remarks/>
        Alert,
        
        /// <remarks/>
        SaveInPhone,
        
        /// <remarks/>
        SaveInSim,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.79.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public enum ReceiveType {
        
        /// <remarks/>
        All,
        
        /// <remarks/>
        UnRead,
        
        /// <remarks/>
        Top,
        
        /// <remarks/>
        Down,
        
        /// <remarks/>
        WithDate,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.79.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class ReceiveSMS {
        
        private string receiveNumberField;
        
        private string smsTextField;
        
        private string dateField;
        
        private string timeField;
        
        private string fromNumberField;
        
        private int errorField;
        
        /// <remarks/>
        public string ReceiveNumber {
            get {
                return this.receiveNumberField;
            }
            set {
                this.receiveNumberField = value;
            }
        }
        
        /// <remarks/>
        public string SmsText {
            get {
                return this.smsTextField;
            }
            set {
                this.smsTextField = value;
            }
        }
        
        /// <remarks/>
        public string Date {
            get {
                return this.dateField;
            }
            set {
                this.dateField = value;
            }
        }
        
        /// <remarks/>
        public string Time {
            get {
                return this.timeField;
            }
            set {
                this.timeField = value;
            }
        }
        
        /// <remarks/>
        public string FromNumber {
            get {
                return this.fromNumberField;
            }
            set {
                this.fromNumberField = value;
            }
        }
        
        /// <remarks/>
        public int Error {
            get {
                return this.errorField;
            }
            set {
                this.errorField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.79.0")]
    public delegate void LoginCompletedEventHandler(object sender, LoginCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.79.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class LoginCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal LoginCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.79.0")]
    public delegate void SendSmsCompletedEventHandler(object sender, SendSmsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.79.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SendSmsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SendSmsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public long[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((long[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.79.0")]
    public delegate void SendSingleSmsCompletedEventHandler(object sender, SendSingleSmsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.79.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SendSingleSmsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SendSingleSmsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public long Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((long)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.79.0")]
    public delegate void SendSmsUDHCompletedEventHandler(object sender, SendSmsUDHCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.79.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SendSmsUDHCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SendSmsUDHCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public long[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((long[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.79.0")]
    public delegate void getCreditCompletedEventHandler(object sender, getCreditCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.79.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getCreditCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getCreditCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.79.0")]
    public delegate void GetReceiveSMSWithNumberCompletedEventHandler(object sender, GetReceiveSMSWithNumberCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.79.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetReceiveSMSWithNumberCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetReceiveSMSWithNumberCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ReceiveSMS[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ReceiveSMS[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.79.0")]
    public delegate void GetReceiveSMSCompletedEventHandler(object sender, GetReceiveSMSCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.79.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetReceiveSMSCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetReceiveSMSCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ReceiveSMS[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ReceiveSMS[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.79.0")]
    public delegate void GetCountAllCompletedEventHandler(object sender, GetCountAllCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.79.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetCountAllCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetCountAllCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.79.0")]
    public delegate void GetCountCompletedEventHandler(object sender, GetCountCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.79.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetCountCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetCountCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.79.0")]
    public delegate void GetDeliveryCompletedEventHandler(object sender, GetDeliveryCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.79.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetDeliveryCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetDeliveryCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.79.0")]
    public delegate void GetSingleDeliveryCompletedEventHandler(object sender, GetSingleDeliveryCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.79.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetSingleDeliveryCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetSingleDeliveryCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.79.0")]
    public delegate void GetAllDeliveryCompletedEventHandler(object sender, GetAllDeliveryCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.79.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetAllDeliveryCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetAllDeliveryCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.79.0")]
    public delegate void SendFutureSmsCompletedEventHandler(object sender, SendFutureSmsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.79.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SendFutureSmsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SendFutureSmsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.79.0")]
    public delegate void DeleteFutureSmsCompletedEventHandler(object sender, DeleteFutureSmsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.79.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class DeleteFutureSmsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal DeleteFutureSmsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.79.0")]
    public delegate void CheckSendFutureCompletedEventHandler(object sender, CheckSendFutureCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.79.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CheckSendFutureCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CheckSendFutureCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591